modLoader="javafml" 
loaderVersion="${forge_loader_version_range}"
license="MIT"

[[mods]]
modId="simple_animator"
version="${version}"
displayName="SimpleAnimator"
logoFile="simple_animator.png"
authors="Louis_Quepierts"
description='''

'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.simple_animator]]
    modId="forge"
    mandatory=true
    versionRange="${forge_loader_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.simple_animator]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
