modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "simple_animator"
version = "${version}"
displayName = "SimpleAnimator"
authors = "Louis_Quepierts"
description = '''

'''
logoFile = "simple_animator.png"

[[dependencies.simpleanimator]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neoforge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.simpleanimator]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[mixins]]
    config = "simple_animator.mixins.json"
